"""Regenerate two figures that carry content-interpretation labels.

fig_s1  : crop to layers 1-3 (physical, word, sentence). Layers 4-5 are the
          markup/content reading, outside this paper's scope.
fig_s7  : regenerate with protocol/statistical rows only.

fig_channels.png is NOT generated here. This script used to contain a stale
block that wrote fig_channels.png titled "The carrier holds no sequential
structure; the five sub-channels do" -- a claim our own recomputation disproved
(PC1 lag-1 z = 463, still +332 after detrending). That block silently overwrote
the correct figure. It was removed 2026-08-13. The correct generator is
fig_channels_honest.py; do not re-add a fig_channels writer here.
"""
import numpy as np
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image

FIG = Path(__file__).resolve().parent.parent / "figures"

# ---------------------------------------------------------------- fig_s1 crop
src = Image.open(f"{FIG}/fig_s1_packet_dissection.png")
w, h = src.size
src.crop((0, 0, w, int(h * 0.497))).save(f"{FIG}/fig_packet_layers.png")
print(f"fig_packet_layers.png  {w}x{int(h*0.497)}  (layers 1-3 only)")

# fig_channels.png is generated by fig_channels_honest.py -- see module docstring.

# ---------------------------------------------------------------- fig_s7 rebuild
# Corrections 2026-08-13: the residual-MI test has not been run on
# FRB 20220912A (the source's own Section 5 box says so), so that cell is
# not-testable, not confirmed. The "25% symbol uniformity" row is REMOVED:
# the paper withdraws that claim as fixed by construction (Section 4.3).
# Row labels use the condensed paper's neutral terminology.
rows = ["sequential MI", "residual MI", "5+1 channel PCA", "Zipf slope",
        "vocabulary growth", "brevity", "32-offset wave",
        "anti-synchronised transitions", "I/Q quadrature",
        "line-code persistence"]
cols_ = ["FRB 121102\n(bulk only)", "FRB 20201124A\n(spectral)", "FRB 20220912A\n(spectral)"]
# 1 = confirmed, 0 = not testable with available data
M = np.array([[1,1,1],[1,1,0],[0,1,1],[1,1,1],[1,1,1],[1,1,1],
              [0,1,1],[0,1,1],[0,1,1],[1,1,1]])
fig, ax = plt.subplots(figsize=(7.4, 5.6))
for i in range(len(rows)):
    for j in range(3):
        ok = M[i, j] == 1
        ax.add_patch(plt.Rectangle((j, len(rows)-1-i), .94, .88,
                     facecolor="#a5d6a7" if ok else "#eeeeee",
                     edgecolor="white", lw=2))
        ax.text(j+.47, len(rows)-1-i+.44, "Y" if ok else "--", ha="center", va="center",
                fontsize=14, fontweight="bold", color="#1b5e20" if ok else "#9e9e9e")
ax.set_xlim(-.02, 3); ax.set_ylim(-1.1, len(rows)+.55)
ax.set_xticks([j+.47 for j in range(3)]); ax.set_xticklabels(cols_, fontsize=9.5, fontweight="bold")
ax.xaxis.set_ticks_position("top")
ax.set_yticks([len(rows)-1-i+.44 for i in range(len(rows))])
ax.set_yticklabels(rows, fontsize=10)
for s in ax.spines.values(): s.set_visible(False)
ax.tick_params(length=0)
n_ok = int(M.sum()); n_grey = int((M == 0).sum())
ax.text(1.47, -.05, f"{n_ok} of {n_ok} testable cells confirmed, none failed\n"
        f"{n_grey} not testable with available data  |  "
        f"protocol and statistical features only",
        ha="center", va="top", fontsize=8.5, style="italic", color="#555555")
fig.tight_layout(); fig.savefig(f"{FIG}/fig_crosssource.png", dpi=200); plt.close(fig)
print(f"fig_crosssource.png written ({n_ok} confirmed, {n_grey} not testable)")
